name: bugeyedbettys
author: Jake Russo
description: Bug Eyed Bettys Website
dependencies:
  angular: any
  angular_dart_ui_bootstrap: any
  angular_ui: any
  browser: any
transformers:
- angular
- $dart2js:
    verbose: true
