name: bugeyedbettys
author: Jake Russo
description: Bug Eyed Bettys Website
dependencies:
  angular: any
  angular_dart_ui_bootstrap: any
  angular_ui:
    git: https://github.com/akserg/angular.dart.ui.git
  browser: any
  shadow_dom: any
transformers:
- angular:
    html_files:
      - lib/component/menu_category.html
      - lib/component/menu_item.html
      - web/view/home.html
      - web/view/menu.html
- $dart2js:
    verbose: true

