name: bugeyedbettys
author: Jake Russo
description: Bug Eyed Bettys Website
dependencies:
  angular: any
  browser: any
  shadow_dom: any
transformers:
- angular:
    html_files:
      - lib/component/menu_category.html
      - lib/component/menu_item.html
      - web/view/home.html
      - web/view/menu.html
      - web/view/about.html
      - web/view/gallery.html
      - web/view/gift-cards.html
      - web/view/specials.html
      - web/view/drinks.html
- $dart2js:
    minify: true

